#!/bin/bash
source /etc/sysconfig/httpd

if [ -z "${PIDFILE}" ]; then
    PIDFILE=/var/run/httpd/httpd.pid
fi

if [ -f "${PIDFILE}" ]; then
    rm "${PIDFILE}"
fi

if [ "$1" == "LOCK" ]; then
    touch /var/www/html/db/lock
fi
chown -R apache:apache /var/www/html

if [ -n "${SERVERNAME}" ]; then
    echo "ServerName ${SERVERNAME}" >>/etc/httpd/conf.d/tiki.conf
    sed -e "s/^#Hostname=.*/Hostname>=${SERVERNAME}/" -i /etc/ssmtp/ssmtp.conf
fi
if [ -n "${SERVERALIAS}" ]; then
    echo "ServerAlias ${SERVERALIAS}" >>/etc/httpd/conf.d/tiki.conf
fi

/usr/sbin/httpd -DFOREGROUND "$@"
