#!/bin/bash
set -e
source /etc/sysconfig/httpd

function setup_data() {
    local DIR=$1
    if [ ! -d /data/${DIR} ]; then
        mkdir -p /data/${DIR}
    fi
    set +e
    /bin/mv /var/www/html/${DIR}/* /data/${DIR}/
    set -e
}

function setup_links() {
    local DIR=$1
    rm -rf /var/www/html/$DIR
    ln -s /data/$DIR /var/www/html/$DIR
    chmod 0777 /data/$DIR
}

if [ -z "${PIDFILE}" ]; then
    PIDFILE=/var/run/httpd/httpd.pid
fi

if [ -f "${PIDFILE}" ]; then
    rm "${PIDFILE}"
fi

if [ -n "$LOCK" ]; then
    touch /var/www/html/db/lock
fi
chown -R apache:apache /var/www/html

if [ -n "$MIGRATE_DATADIR" ]; then
    setup_data "dump"
    setup_data "files"
    setup_data "img/wiki"
    setup_data "img/wiki_up"

    if [ ! -d /data/db ]; then
        mkdir -p /data/db
    fi
    if [ ! -f /data/db/local.php]; then
        cp /var/www/html/db/local.php /data/db/local.php
    fi
  
    if [ ! -d /data/ssl ]; then
        mkdir -p /data/ssl
    fi
    if [ ! -f /data/ssl/server.key ]; then
        cp /etc/pki/tls/private/server.key /data/ssl/server.key
    fi
    if [ ! -f /data/ssl/server.crt ]; then
        cp /etc/pki/tls/certs/server.crt /data/ssl/server.crt
    fi
    if [ ! -f /data/ssl/chain.crt ]; then
        if [ -f /etc/pki/tls/certs/chain.crt ]; then
            cp /etc/pki/tls/certs/chain.crt /data/ssl/chain.crt
        fi
    fi
    exit 0
fi
if [ -n "$DATADIR" ]; then
    setup_links "dump"
    setup_links "files"
    setup_links "img/wiki"
    setup_links "img/wiki_up"
    set +e
    rm /var/www/html/db/local.php
    ln -s /data/db/local.php /var/www/html/db/local.php
    chmod 0777 /data/db
    cp /data/ssl/*.crt /etc/pki/tls/certs/
    cp /data/ssl/*.key /etc/pki/tls/private/
    set -e
fi

if [ -n "${SERVERNAME}" ]; then
    sed -e "s/ServerName.*/ServerName ${SERVERNAME}/" -i /etc/httpd/conf.d/tiki.conf
    sed -e "s/^#Hostname=.*/Hostname>=${SERVERNAME}/" -i /etc/ssmtp/ssmtp.conf
fi
if [ -n "${SERVERALIAS}" ]; then
    sed -e "s/#ServerAlias./ServerAlias ${SERVERALIAS}/" -i /etc/httpd/conf.d/tiki.conf
fi
if [ -f /etc/pki/tls/certs/chain.crt ]; then
    sed -e 's/#SSLCertificateChainFile/SSLCertificateChainFile/' -i /etc/httpd/conf.d/tiki.conf
fi
/usr/sbin/httpd -DFOREGROUND "$@"
